### ISSUE TITLE
Wat doet het?

### ISSUE THREAD

**Issue by Wouterr0** [Luigit12/Luigit12.github.io#1]
Als ik naar Luigit12.github.io dan staat er alleen Hey.
btw, waarom had je dat unity web dinges weggehaald? En waarom zijn al je commits genaamt "Initial commit"?

**Comment by Wouterr0** [comment]
Ook zou ik .DS_store in een .gitignore file doen want dat is alleen voor mac.

**Comment by Luigit12** [comment]
Wat doet de ds_store in mac eigenlijk?

**Comment by Wouterr0** [comment]
¯\_(ツ)_/¯ hier <https://en.wikipedia.org/wiki/.DS_Store>
